[mgr]
prepend_keymap = [
	{ on = [
		"g",
		"i",
	], run = "cd ~/tui/illustrations", desc = "go to tui illustrations" },
	{ on = [
		"g",
		"d",
	], run = "cd ~/Downloads", desc = "go to downloads" },
	{ on = [
		"g",
		"b",
	], run = "back", desc = "go back" },

	{ on = "d", run = "remove --permanently", desc = "Permanently delete" },
]
